version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  worker:
    build: .
    container_name: celery_worker
    volumes:
      - .:/app
    command: celery -A backend worker -l INFO
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq/
  beat:
    build: .
    container_name: beat
    volumes:
      - .:/app
    command: celery -A backend beat -l INFO
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq/