FROM python:3.10

WORKDIR /app

ENV PYTHONUNBUFFERED=1

ARG EXTRA_DEV_DEPS=""

RUN apt-get update 

RUN pip install poetry==1.4.0

COPY pyproject.toml .
COPY poetry.lock .
ARG POETRY_VIRTUALENVS_CREATE=false

RUN pip install pip==23.0.1 && \
    poetry install -n --no-ansi --no-root

COPY . .


EXPOSE 8000

