version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  worker:
    build: .
    container_name: celery_worker
    volumes:
      - .:/app
    command: celery --app motorista.celery:app worker -Q motorista,celery --loglevel DEBUG
    depends_on:
      - rabbitmq
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=5672
      - BROKER_USER=guest
      - BROKER_PASSWORD=guest