# Generated by Django 4.2.3 on 2023-07-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_asset_interval_remove_asset_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="long_name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="short_name",
            field=models.TextField(null=True),
        ),
    ]
