# Generated by Django 4.2.3 on 2023-07-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_asset_long_name_alter_asset_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="symbol",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="assetrecord",
            name="measured_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
