# Generated by Django 4.2.3 on 2023-08-02 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_asset_symbol_alter_assetrecord_measured_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="useralert",
            name="last_checked",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
