# Generated by Django 4.2.3 on 2023-08-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_useralert_last_checked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useralert",
            name="last_checked",
            field=models.DateTimeField(null=True),
        ),
    ]
