# Generated by Django 4.2.3 on 2023-08-07 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_useralert_last_checked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetrecord",
            options={"ordering": ["-measured_at"]},
        ),
    ]
